default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todolist_development
  username: todolist_user
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: todolist_test
  username: todolist_user
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: todolist_production
  username: todolist_user
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>
